package enums;

/**
 * Collection of menus available in the GUI
 */
public enum Menu
{
    MAIN_MENU, NICKNAME_SERVER_CONNECTION, SETTINGS, MULTIPLAYER_GAME_TYPE, SINGLEPLAYER_GAME_TYPE, LOBBY,
    TEAM_MATCH_SINGLEPLAYER, TEAM_MATCH_MULTIPLAYER,
    CAPTURE_THE_FLAG_SINGLEPLAYER, CAPTURE_THE_FLAG_MULTIPLAYER,
    END_GAME,
    HELP
}
